window.characterData = window.characterData || {}; window.characterData.bastet = {
                        id: 'bastet',
                        name: 'Bastet',
                        title: 'Przebudzona Bogini',
                        unlocked: false,
                        unlockCost: 20000,
                        level: 0,
                        baseCost: 800,
                        costGrowth: 1.3,
                        baseLpPerSecond: 60,
                        bondPoints: 0,
                        baseBpPerSecond: 1.5,
                        storyProgress: 0,
                        avatar: 'imgs/avatars/bastet_avatar.png',
                        image: 'imgs/characters/bastet.png',
                        clickImage: 'imgs/click/bastet_click.png',
                        bio: [ 
                            { threshold: 0, text: "Piękna istota o kocich uszach i ogonie, która zamieszkała w starożytnej świątyni. Władcza i kapryśna, ale z ukrytą zmysłowością." },
                            { threshold: 3, text: "Za fasadą arogancji kryje się namiętna natura i desperacka potrzeba bliskości. Lubi dominować, ale równie mocno pragnie być pożądana." },
                            { threshold: 6, text: "Odkrywa, że prawdziwa władza leży w obopólnej przyjemności i oddaniu. Jej kocie instynkty prowadzą ją ku coraz śmielszym ekspresjom." }
                        ],
                        clickComments: ["Mmm~ Tak trzymaj...", "Dotykaj mnie więcej...", "Ach! Właśnie tam!", "Jesteś mój...", "*mruczenie rozkoszy*"],
                        storyThresholds: [0, 1500, 4000, 8000, 15000, 25000, 40000, 60000, 85000, 120000],
                        storyEvents: [
                            { id: 'bastet_1', title: "Spotkanie w Świątyni", cg: "imgs/cg/bastet/bastet_1.png", text: "W opuszczonej świątyni znajdujesz piękną, egzotyczną kobietę o kocich uszach wypoczywającą w słońcu. Budzi się leniwym ruchem i patrzy na ciebie z mieszanką ciekawości i pogardy. 'Och? Gość...' mruczy, przeciągając się zmysłowo. 'Dawno nikt tu nie zaglądał. Jestem Bastet.' Wstaje z gracją kotki, jej ciało porusza się hipnotyzująco. 'Skoro tu jesteś... może zostaniesz? Nudzę się okropnie.'" },
                            { id: 'bastet_2', title: "Test Oddania", cg: "imgs/cg/bastet/bastet_2.png", text: "Bastet siada na kamiennym tronie i patrzy na ciebie wyzywająco. 'Chcesz zostać? To pokaż mi swoją... devotion.' Wyciąga stopę w twoją stronę. 'Pocałuj ją.' Gdy się wahasz, jej oczy błyszczą niebezpiecznie. Klękasz i całujesz jej stopę - jest ciepła i miękka. Bastet wydaje zadowolony dźwięk. 'Mmm... może jednak coś z ciebie będzie.' Jej ogon łasi się, gdy kontynuujesz. 'Wyżej... całuj wyżej...'" },
                            { id: 'bastet_3', title: "Pierwsze Odkrycie", cg: "imgs/cg/bastet/bastet_3.png", text: "Bastet prowadzi cię do ukrytego basenu w świątyni. 'Potrzebuję kąpieli,' oznajmia, zaczynając zdejmować swoje minimalne stroje. Jej ciało jest perfekcyjne, a ona wie o tym. 'Będziesz mi towarzyszyć. I nie, nie odwracaj się!' Wchodzi do wody, jej ruchy są czysto seksualne. 'Chodź... odmyj mnie.' Gdy zaczynasz myć jej plecy, mruczy z przyjemności. 'Niżej... i nie bądź taki nieśmiały.'" },
                            { id: 'bastet_4', title: "Namiętny Impuls", cg: "imgs/cg/bastet/bastet_4.png", text: "Po kąpieli Bastet popycha cię na miękkie poduszki. 'Podobasz mi się,' mruczy, siadając ci na biodrach. Jej ciało jest ciepłe i wilgotne po kąpieli. 'Dotykaj mnie... wszędzie.' Prowadzi twoje ręce po swoim ciele, jej oddech przyspiesza. Gdy dotykasz jej piersi, wyściska głośno. 'Tak! Dokładnie tak...' Jej biodra zaczynają się poruszać rytmicznie. 'Chcę cię... teraz.'" },
                            { id: 'bastet_5', title: "Dzika Dominacja", cg: "imgs/cg/bastet/bastet_5.png", text: "Bastet wpada do komnaty jak dzika bestia, jej oczy płoną nieludzkim głodem. Rzuca się na ciebie, przewracając na ziemię. Jej pazury drapią twoją skórę, zostawiając czerwone ślady. Nie mówi ani słowa - tylko warczy jak kotka w rui. Siada na tobie i prowadzi twojego kutasa do swojej mokrej cipki jednym brutalnym ruchem. Jej krzyk rozkoszy odbija się echem od ścian, gdy zaczyna jeździć na tobie z dziką desperacją. Jej piersi podskakują, pot kapie na twoją twarz, a ona drapie twoje ramiona tak mocno, że lecze krew." },
                            { id: 'bastet_6', title: "Słodka Zemsta", cg: "imgs/cg/bastet/bastet_6.png", text: "Następnego dnia Bastet budzi cię, wiążąc twoje ręce jedwabnymi szarfami. 'Teraz ja będę dominować,' mruczy z przewrotnym uśmiechem. Siada na twojej twarzy bez ostrzeżenia. 'Liż mnie... i nie przestawaj.' Jej soki kapią ci na twarz, gdy porusza biodrami. 'Jesteś moją zabawką... moim osobistym niewolnikiem do rozkoszy.' Dochodzi głośno na twoich ustach, potem się nachyla. 'A teraz... moja kolej na zabawę z tobą.'" },
                            { id: 'bastet_7', title: "Nocne Łowy", cg: "imgs/cg/bastet/bastet_7.png", text: "Środek nocy - Bastet budzi cię, całując i gryząc twoją szyję. 'Nie mogę spać... jestem napalona,' szepcze, jej ręka wędruje w dół. 'Będziemy się pieprzyć do świtu.' Wskazuje różne pozycje po całej świątyni. 'Tutaj... i tam... i na tym tronie...' Przez całą noc pieprzysz ją w każdym kącie, jej krzyki echują po kamiennych ścianach. 'Jeszcze! Jeszcze! Wypełnij mnie swoim nasieniem!'" },
                            { id: 'bastet_8', title: "Magiczna Przemiana", cg: "imgs/cg/bastet/bastet_8.png", text: "Bastet prowadzi cię do tajemnej komnaty pełnej starożytnych symboli. 'Chcę ci pokazać coś... specjalnego,' szepcze, kreśląc palcem magiczne znaki na swojej skórze. Jej oczy zaczynają świecić złotym blaskiem, a z jej ciała emanuje ciepło. 'To starożytna magia... magia rozkoszy...' Gdy ją dotykasz, czujesz elektryzujące wibracje przechodzące przez jej skórę. Jej orgazmy stają się nieludzko intensywne, a jej krzyki mają nadprzyrodzoną melodię. 'Mogę... mogę sprawić, że będziesz dochodzić bez końca...'" },
                            { id: 'bastet_9', title: "Desperacka Żądza", cg: "imgs/cg/bastet/bastet_9.png", text: "Budzisz się i zastajasz Bastet klęczącą przy łóżku, drżącą z pożądania. Jej oddech jest urywany, oczy szkliste. Bez słowa chwyci twojego kutasa i bierze go głęboko do ust, jakby umierała z pragnienia. Jej gardło kurczy się wokół ciebie, podczas gdy masturbuje się drugą ręką. Łzy spływają jej po policzkach - nie z bólu, ale z czystej rozkoszy i ulgi. Gdy dochodzisz, połyka każdą kroplę, potem całuje twoje biodra, wciąż drżąc. Bez słowa kładzie się obok i przytula do ciebie jak kotka, która w końcu znalazła dom." },
                            { id: 'bastet_10', title: "Rytuał Wieczności", cg: "imgs/cg/bastet/bastet_10.png", text: "Bastet budzi cię o północy, jej oczy płoną magicznym blaskiem. Bez słowa prowadzi cię do serca świątyni, gdzie przygotowała tajemniczy rytuał. Okrągłe łóżko otoczone jest płonącymi świecami i starożytnymi symbolami. 'To ostatni rytuał,' szepcze, zdejmując wszystkie ozdoby. Kładzie się na łóżku i rozsuwa nogi, pokazując swoją mokrą cipkę. 'Połącz się ze mną... na zawsze.' Gdy w nią wchodzisz, cała świątynia zaczyna pulsować rytmem waszych ciał. Symbole na ścianach świecą, a jej orgazm wstrząsa całym miejscem. Czujesz jak magia was łączy - teraz jesteś częścią tej świątyni, a ona częścią ciebie." }
                        ]
                    };
